### ISSUE TITLE
Can't make POST request with `'Content-Type': 'application/x-www-form-urlencoded'`

### ISSUE THREAD

**Issue by aphiwadchh** [apollographql/datasource-rest#113]
Hi, thanks making a great library.
I'm having problem with making POST request with `'Content-Type': 'application/x-www-form-urlencoded'`

What I've tried:
1. Passing body as JSON object
```typescript
const response = await this.post(path,
            {
                headers: {
                    'content-type': 'application/x-www-form-urlencoded'
                },
                body: { foo: 'bar', fooz: 'baz' }
            })
```
This doesn't work because I think `x-www-form-urlencoded` expects body to be in 'foo=bar&fooz=baz'

2. Passing body as string
```typescript
const response = await this.post(path,
{
    headers: {
        'content-type': 'application/x-www-form-urlencoded'
    },
    body: 'foo=bar&fooz=baz'
})

```
This also doesn't work, the body didn't seems to get set. I dive a little, and see it's undefined:
```javascript
{
  method: 'POST',
  headers: { 'content-type': 'application/x-www-form-urlencoded' },
  body: undefined,
  params: URLSearchParams {}
}
```
causing by this if statement check https://github.com/apollographql/datasource-rest/blob/v4.3.2/src/RESTDataSource.ts#L228

3. Passing body as URLSearchParams following this example of node-fetch https://github.com/node-fetch/node-fetch#post-with-form-parameters
```typescript
const formData = new URLSearchParams();
formData.append('foo', 'bar');
formData.append('fooz', 'baz');

const response = await this.post(path,
            {
                body: formData
            })
```
This doesn't work, similar case with (2); the body is undefined:
```javascript
{
  method: 'POST',
  body: undefined,
  params: URLSearchParams {},
  headers: [Object: null prototype] {}
}
```

I might be doing this wrong, very much appreciated if anyone know a proper way to send this type of POST request with `'Content-Type': 'application/x-www-form-urlencoded'`; or a workaround for this.

**Comment by trevor-scheer** [comment]
This should be resolved via https://github.com/apollographql/datasource-rest/pull/89 in the next major release (coming relatively soon - on the order of week to weeks).

**Comment by aphiwadchh** [comment]
@trevor-scheer Thanks a lot for quick response. Looking forward to the new release!

**Comment by jkepps** [comment]
has anyone been able to verify that this was resolved in v5? i'm still running into an issue with a request that needs to use `x-www-form-urlencoded` for the content-type header

**Comment by trevor-scheer** [comment]
Thanks for the follow-up @jkepps, and glad it's working for you!
