### ISSUE TITLE
Next release of package @apollo/datasource-rest

### ISSUE THREAD

**Issue by MarkAPhillips** [apollographql/datasource-rest#130]
I am currently using version 4.3.2 of the package - as am in the process of migrating to Apollo 4 - I noticed that there is a lot of discrepancies in the current docs and the actual public release - two key areas was the signatures of willSendRequest and also the removal of didReceiveResponse hooks - the last release was in Oct - are you expecting to update the package soon so the docs and current release are aligned correctly as am finding it quite confusing esp. when trying to migrate from Apollo 3 especially as I am using typescript - I would assume also these changes are breaking changes so would expect a new major release.

If I am wrong let me know - thanks

**Comment by glasser** [comment]
The release of v5 is being tracked at https://github.com/apollographql/datasource-rest/pull/93. We didn't quite get it out before some vacations started but it should be next week.

**Comment by MarkAPhillips** [comment]
Thanks @glasser  - look forward to the new release !
