### ISSUE TITLE
RESTDataSource’s willSendRequest parameter changes

### ISSUE THREAD

**Issue by grego-e** [apollographql/datasource-rest#135]
We are migrating an Apollo server to version 4 and noticed that with the new `@apollo/datasource-rest` module the behaviour of `willSendRequest`’s `request` argument has changed. It no longer contains the `path` field that it had with `apollo-datasource-rest`. 

According to the latest docs https://github.com/apollographql/datasource-rest#intercepting-fetches , `willSendRequest`’s first argument is the `path` but that is not yet available in the latest released version 4.3.2.

I see that with the following PR https://github.com/apollographql/datasource-rest/pull/89/files the functionality was merged but it’s not released yet. Could a version be released with that functionality, please?

Secondly, at the moment in `willSendRequest` we’re not just updating and adding headers but also doing some modifications to the path. Is this a right place for doing that in your view or would you move that somewhere else?

Thanks

**Comment by grego-e** [comment]
The v5 release should fix this. Thanks a lot @trevor-scheer ❤️

**Comment by trevor-scheer** [comment]
Thanks for reporting! In hindsight we should've done this work on a separate `version-5` branch, but the intent was for this to all happen relatively quickly so we weren't as diligent as we could've been. Sorry for the confusion and happy v5 day!
