### ISSUE TITLE
willSendRequest this.context does not exist on  xxxxDataSource

### ISSUE THREAD

**Issue by MarkAPhillips** [apollographql/datasource-rest#140]
Firstly thank you for releasing v5.0.0 

When extending RestDataSource when overriding willSendRequest - I now receive a type error that `this.context` does not exist  (Typescript version 4.7.4) - previously this worked as is.

What is the preferred method to access the context in the willSendRequest?
I am setting the context value using expressMiddleware as defined in the here
https://www.apollographql.com/docs/apollo-server/api/express-middleware/

It is not apparent from the current docs here https://github.com/apollographql/datasource-rest#intercepting-fetches

**Comment by trevor-scheer** [comment]
Hey @MarkAPhillips, `RESTDataSource` is no longer aware of `context`, but you can make it so in your implementation. Previously, `context` was set for you via a little bit of magic in Apollo Server's `dataSources` configuration option. Now it's up to you how you'd like to go about that (presumably in your server's `context` function).

Here I've added it my data source's `constructor`, so I provide the context to it when I instantiate it.
```ts
class MyDS<TContext> extends RESTDataSource {
  context: TContext;

  constructor(config: DataSourceConfig, context: TContext) {
    super(config);
    this.context = context;
  }
}
```

I'd also recommend _not_ passing the whole context object, but rather just what information the datasource needs.

I'll update the README with a fix, thanks for pointing that out 👍
