### ISSUE TITLE
Configuring external caching in Apollo v4

### ISSUE THREAD

**Issue by dycor** [apollographql/datasource-rest#149]
Hello,

I found a problem with "Configuring external caching" in Apollo v4
[DOCUMENTATION](https://www.apollographql.com/docs/apollo-server/performance/cache-backends#configuring-external-caching)

In Apollo v3 i use the following code with Redis
```js
import Keyv from 'keyv';
import { KeyvAdapter } from '@apollo/utils.keyvadapter';

const server = new ApolloServer({
  // ...,
  cache: new KeyvAdapter(new Keyv('...MyConnectionString...')), 
});

```
If I log the keyvalue used in `apollo-datasource-rest/src/HTTPCache.ts`

```js
PrefixingKeyValueCache {
   wrapped: KeyvAdapter {
       keyv: Keyv {
           _events: [Object: null prototype],
           _eventsCount: 1,
       _maxListeners: undefined,
       opts: [Object],
       iterator: [AsyncGeneratorFunction (anonymous)],
       [Symbol(kCapture)]: false
     },
       dataLoader: DataLoader {
           _batchLoadFn: [Function (anonymous)],
       _maxBatchSize: Infinity,
       _batchScheduleFn: [Function (anonymous)],
       _cacheKeyFn: [Function (anonymous)],
       _cacheMap: null,
       _batch: [Object]
     }
   },
   prefix: 'httpcache:'
 }
```
I can see the KeyValue it is well taken into consideration and it work with no problem.
But in Apollo v4 it doesn't work.
The log of the KeyValue in `@apollo/datasource-rest/HTTPCache.ts` it's

```js

PrefixingKeyValueCache {
   wrapped: InMemoryLRUCache {
     cache: LRUCache {
           max: 0,
       maxSize: 31457280,
       maxEntrySize: 31457280,
       sizeCalculation: [Function: sizeCalculation],
           fetchMethod: null,
       fetchContext: undefined,
       keyMap: Map(0) {},
           keyList: [],
       valList: [],
       next: [],
       prev: [],
       head: 0,
       tail: 0,
       free: [],
       initialFill: 1,
       size: 0,
       disposeAfter: null,
       disposed: null,
       noDisposeOnSet: false,
       noUpdateTTL: false,
       noDeleteOnFetchRejection: false,
       calculatedSize: 0,
       sizes: ZeroArray(0) [],
       removeItemSize: [Function (anonymous)],
       requireSize: [Function (anonymous)],
       addItemSize: [Function (anonymous)],
       allowStale: false,
       noDeleteOnStaleGet: false,
       updateAgeOnGet: false,
       updateAgeOnHas: false,
       ttlResolution: 1,
       ttlAutopurge: false,
       ttl: 0
     }
   },
   prefix: 'httpcache:'
 }
```

The KeyValue chosen it's not used and in the following [documentation](https://www.apollographql.com/docs/apollo-server/performance/cache-backends#configuring-external-caching) we have no more informations about this.

After an investigation in source code, I found this solution

```js
import {
  RESTDataSource as ApolloRESTDataSource,
} from '@apollo/datasource-rest';

export class RESTDataSource extends ApolloRESTDataSource {
//...

  constructor(name: string) {
   const cache = new KeyvAdapter(new Keyv('...MyConnectionString...'));
    super({cache});
  }
//...
```

It works but it's not normal to do this.

**Comment by trevor-scheer** [comment]
In AS4 there's no longer any magic around how data sources are created. In v3 as you've pointed out, the server cache (and context) were shared with your data sources automatically.

The migration guide explains how to replicate this old behavior if you like:
https://www.apollographql.com/docs/apollo-server/migration/#datasources

Does that approach fix the issue for you?

I'm not sure the [caching docs](https://www.apollographql.com/docs/apollo-server/performance/cache-backends/#implementing-your-own-cache-backend) that you linked to need to concern themselves with `RESTDataSource`. Maybe the README should mention the `cache` configuration option and show the migration path?

**Comment by dycor** [comment]
The [caching docs](https://www.apollographql.com/docs/apollo-server/performance/cache-backends/#implementing-your-own-cache-backend) it's not up to date because if I only do what it says, the caching doesn't work

```js
import Keyv from "keyv";
import { KeyvAdapter } from "@apollo/utils.keyvadapter";

const server = new ApolloServer({
  typeDefs,
  resolvers,
  cache: new KeyvAdapter(new Keyv("redis://user:pass@localhost:6379")), 
});
```
I have to do the behavior in https://www.apollographql.com/docs/apollo-server/migration/#datasources
Thanks for the response

**Comment by trevor-scheer** [comment]
@dycor right. What I'm saying is: the article you're linking to is not specific to `RESTDataSource` (or any data source for that matter). That article pertains to configuring the server's cache. If you choose to share that cache with data sources, that's a different concern. Maybe something we could document [here](https://www.apollographql.com/docs/apollo-server/data/fetching-data#batching-and-caching)?
