### ISSUE TITLE
Apollo Datasource adds content-type: header when Content-Type (case sensitive) header is set

### ISSUE THREAD

**Issue by AaronMoat** [apollographql/datasource-rest#153]
https://github.com/apollographql/datasource-rest/blame/9a8b6278d80bc677fa7608ac0c3f065d991a79af/src/RESTDataSource.ts#L486 

If this.get or similar is called with `headers: { 'Content-Type': 'x' }`, two duplicate headers get set (content-type and Content-Type). 

This can cause problems in the API resulting in problematic behaviour.

**Comment by glasser** [comment]
Looks like a PR was filed (by a colleague of yours?): #154.

**Comment by AaronMoat** [comment]
Not a colleague of mine, just seem to have run into the same problem at the same time :)

**Comment by JustinSomers** [comment]
@AaronMoat We were able to get #154 merged in:
https://github.com/apollographql/datasource-rest/commit/bb0cff0e1cb9e8adb13587fc9d99ea573be4cc32
