### ISSUE TITLE
RESTDataSource no longer have access to all datasources through context

### ISSUE THREAD

**Issue by grego-e** [apollographql/datasource-rest#158]
With `apollo-datasource-rest` every datasource had access to all the other datasources through `context.dataSources`. We have numerous instances where a function in one datasource wants to call another function in a different datasource and previously this was achieved through `this.context.dataSources.actualDataSource.actualFunction`. With `@apollo/datasource-rest` this is no longer the case as dataSources is not present in context anymore. 
How would you suggest supplying the needed datasources for the above?

Thank you.

**Comment by glasser** [comment]
You can put a `dataSources` field on your context yourself, just like you can put any other field on your context.

**Comment by grego-e** [comment]
Thank you for the suggestion.
