### ISSUE TITLE
@apollo/datasource-rest willSendRequest param type missing `agent`

### ISSUE THREAD

**Issue by taylorquinn** [apollographql/datasource-rest#189]
WIth `apollo-datasource-rest`, `willSendRequest` took in `requestOptions` of type `RequestOptions`. This object had the property `agent`. This allowed us to pass in a https.Agent with certs. 

Migrating to `@apollo/datasource-rest`, `requestOptions` is now of type `AugmentedRequest`, which is missing `agent`. Is there a new recommended way to set the agent or make a request with the agent? 

` protected willSendRequest?(
    path: string,
    requestOpts: AugmentedRequest,
  ): ValueOrPromise<void>;`

**Comment by trevor-scheer** [comment]
I don't _quite_ follow what the request is here, but I think I get the gist. The datasource calls `willSendRequest`, so it's a little unclear what you mean by passing an `https.Agent` to it since user code isn't calling that function.

Would you like to be able to pass a configured `https.Agent` to the constructor or the `get`, `post` etc. functions? Or do you actually want _access_ to the agent from within `willSendRequest`?

**Comment by taylorquinn** [comment]
Passing a configured https.Agent to the constructor or the get, post etc. functions would definitely be better!

**Comment by singhularity** [comment]
We have the same issue, we need to configure https.Agent on our requests which doesn't seem possible anymore

**Comment by singhularity** [comment]
Was able to work around this by doing the following

const buildProxiedFetcher = (proxy: HttpsProxyAgent) => (
    url: RequestInfo,
    init?: RequestInit
): Promise<NodeFetchResponse> => {
  init = {agent: proxy, ...init}
  return nodeFetch(url, init);
}

Pass the "proxied fetcher" in the datasource constructor. This does mea that all methods will now be going through the proxy though

**Comment by trevor-scheer** [comment]
Thanks @singhularity - I was working on a similar snippet so I'll just paste it as well. @taylorquinn is this sufficient for your use case?

```ts
import fetch from 'node-fetch';
import { Agent } from 'https';
async function customFetcher(url: RequestInfo, init?: RequestInit) {
  return fetch(url, {
    ...init,
    agent: new Agent({ rejectUnauthorized: false }),
  });
}
const dataSource = new (class extends RESTDataSource {
  override baseURL = apiUrl;

  async getFoo() {
    return this.get('foo');
  }
})({
  fetch: customFetcher,
});
```

**Comment by trevor-scheer** [comment]
Happy to reopen if this doesn't address the issue.

**Comment by MarvinXu** [comment]
So [this solution](https://github.com/apollographql/apollo-server/issues/2090#issuecomment-451926660) doesn't work anymore?
