### ISSUE TITLE
RESTDataSource - body based cacheKeyFor POST request

### ISSUE THREAD

**Issue by shinyaohira** [apollographql/datasource-rest#205]
I would like to use cache keys with request body for POST requests.

```typescript
  protected cacheKeyFor(request: Request): string {
    return request.text(); // This type is Promise<string>
  }
```

Current cacheKeyFor interface in RESTDataSource provides a `request` object but it seems it doesn't contains simple body text.
Please help.

**Comment by trevor-scheer** [comment]
This is available as of `@apollo/datasource-rest` v5.
https://github.com/apollographql/datasource-rest/pull/110
