### ISSUE TITLE
Emit caching metrics for `apollo-datasource-rest`

### ISSUE THREAD

**Issue by landau** [apollographql/datasource-rest#22]
Package: `apollo-datasource-rest`

It would be useful to emit metrics around caching. More specifically, some boolean value that indicates when a request results from the cache vs HTTP.  In this way, I would be able to emit metrics for my application and adjust TTLs based on those statistics https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/HTTPCache.ts#L116-L146

Thank you

**Comment by glasser** [comment]
We're going to solve #41 by making each `fetch` call return information about whether or not the call was cached. You can override the protected `fetch` method in your subclass to look at this information and feed it into your metrics system if you'd like. So I'm considering this (old, sorry!) issue to be a duplicate of #41.
