### ISSUE TITLE
Feature request: More control over readResponseAndWriteToCache method

### ISSUE THREAD

**Issue by antho1jp** [apollographql/datasource-rest#223]
In the below private method, I would like to be able to read the body of the response to determine if it should be cached or not. I've tried using `cacheOptions` and cloning the response but that causes a back pressure issue with large reponses. 

The reason is in our REST API responses (example Product Search from OCAPI Salesforce Commerce Cloud) we will get a response for zero results but the body includes other information in it, it's not just an empty body. By using the URL as the key often times these OCAPI requests include parameters in the URL with user input.  Example is search terms like `hostname/product_search?q=something`. So the potential for cache stuffing is a issue. We could just not cache all urls with user input in the request params, however, that would lead to poor performance for common search requests.

Ideally we'd like to just not cache where the response body has some criteria check. In my Product Search example `response.body.count` would be 0. But different ruleset for different endpoints would need to be configured. 

I would say the easiest way to configure would be allowing for the HTTPCache to be extended and the private  method and properties to be overridden. I'm not sure if that would cause any issues elsewhere so I'm not outright proposing that to be the solution. 

```
  private async readResponseAndWriteToCache({
      response,
      policy,
      ttl,
      ttlOverride,
      cacheKey,
    }: {
      response: FetcherResponse;
      policy: CachePolicy;
      ttl: number | null | undefined;
      ttlOverride: number | undefined;
      cacheKey: string;
    }): Promise<void> {
      const body = await response.text();

     // here is where I'd like to put some logic to validate

      const entry = JSON.stringify({
        policy: policy.toObject(),
        ttlOverride,
        body,
      });

      await this.keyValueCache.set(cacheKey, entry, {
        ttl,
      });
    }
```

If there is another solution with the existing package as is I would be interested to know. 

Thank you in advance for any help.

**Comment by trevor-scheer** [comment]
So like a `shouldCache: (responseBody) => boolean` hook that users can implement? Probably ok - I'd have to take a closer look at the code to be sure, but that seems reasonable.

Right now, you could implement your own `KeyValueCache` to pass to the data source with a custom `set` method that handles your exceptions correctly. How do you feel about that approach instead of a new hook?

**Comment by antho1jp** [comment]
> So like a `shouldCache: (responseBody) => boolean` hook that users can implement? Probably ok - I'd have to take a closer look at the code to be sure, but that seems reasonable.
> 
> Right now, you could implement your own `KeyValueCache` to pass to the data source with a custom `set` method that handles your exceptions correctly. How do you feel about that approach instead of a new hook?

That's actually a great idea, I didn't even think of that. I'll give that a try thank you!

**Comment by antho1jp** [comment]
@trevor-scheer just wanted to come back and say that worked like a charm! thanks again!

**Comment by trevor-scheer** [comment]
Great, happy to hear it!
