### ISSUE TITLE
RESTDataSource fail to fetch urn-like resources

### ISSUE THREAD

**Issue by evgenykireev** [apollographql/datasource-rest#23]
This is a bug report.
- Package: apollo-datasource-rest
- Version: latest

Fetching resources that are url-like does not work as expected.

Unit test to reproduce:

```js
it('fails with urn-like resource', async () => {
      const dataSource = new (class extends RESTDataSource {
        baseURL = 'https://api.example.com';

        getFoo() {
          return this.get('/urn:foo:1');
        }
      })();

      dataSource.httpCache = httpCache;

      fetch.mockJSONResponseOnce();

      await dataSource.getFoo();

      expect(fetch.mock.calls.length).toEqual(1);
      expect(fetch.mock.calls[0][0].url).toEqual('https://api.example.com/urn:foo:1');
    });
```

The issue is caused by a combination of [URL](https://nodejs.org/api/url.html) behavior and normalization logic in
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L74-L88 

A better approach would be to remove an ending `/` from `baseURL` and add a leading `/` to `path`. E.g.

```js
protected resolveURL(request: RequestOptions): ValueOrPromise<URL> {
    const normalizedPath = request.path.startsWith('/')
      ? request.path
      : request.path.concat('/');
    
    const baseURL = this.baseURL;
    if (baseURL) {
      const normalizedBaseURL = baseURL.endsWith('/')
        ? baseURL.substring(0, baseURL.length - 1)
        : baseURL;
      return new URL(normalizedPath, normalizedBaseURL);
    } else {
      return new URL(normalizedPath);
    }
}
```
however it breaks a few existing tests.

**Comment by glasser** [comment]
@brandon-leapyear had a similar suggestion on #36

```
let prefix = '', baseURL = undefined
if (this.baseURL) {
  const base = new URL(this.baseURL)
  const basePath = base.pathname
  prefix = basePath.endsWith('/') ? basePath : basePath.concat('/')
  baseURL = base.origin
}

return new URL(prefix + path, baseURL)
```

**Comment by glasser** [comment]
Part of the issue is that 259206037 was just an odd choice.  Given that you can write both `this.get('foo')` and `this.get('/foo')`, it's not clear to me that it was correct to make both of them mean (if base URL is https://x.com/bar) https://x.com/bar/foo; it would be more compatible with how URLs work in HTML if they actually were different. But probably not worth trying to change this since it would break tons of users at runtime.

**Comment by glasser** [comment]
As a pretty simple workaround, you can write `this.get('./urn:foo:1')` which appears to work properly.

That's one approach. Actually fixing this properly seems to either involve moving away from the use of `new URL(path, base)` entirely, or making a big backwards-incompatible change to be "all in" on that approach.  I'm leaning towards the latter but it will break a lot of users. Going to try it out and see what it looks like.
