### ISSUE TITLE
RESTDataSource delete method doesn't work using context header

### ISSUE THREAD

**Issue by longueiraemiliano** [apollographql/datasource-rest#25]
```
// CODE BELOW DOESN'T WORK
await this.delete(`contacts/${contactId}`, undefined, { headers: this.context.req.headers });
await this.fetch({ method: 'DELETE', path: `contacts/${contactId}`, headers: this.context.req.headers });

// CODE BELOW WORKS
await this.delete(`contacts/${contactId}`);
```

Why I cannot set a custom header to do a delete operation? For `post` and `patch` actions works fine, but no for `delete`. Why is that so?

**Comment by trevor-scheer** [comment]
From looking at the code, this should work (in it's now updated form).
In this comment: https://github.com/apollographql/datasource-rest/issues/52#issuecomment-1275295894, the user claims that delete works with headers.

`delete` now accepts 2 arguments: the path, and the requestinit object (which can accept headers).

If this issue still persists I'm happy to reopen with a reproduction.
