### ISSUE TITLE
Parse blob data

### ISSUE THREAD

**Issue by Sean-Y-X** [apollographql/datasource-rest#255]
I have an API that returns pdf blob data. Tested via Postman that I could get a pdf.

However via datasource-rest, the result of the `parsedBody` is `{}`. I tried the latest version and used both `get` and `fetch` methods.

Seems that the blob data was not parsed correctly. I'll do more research next week and post any further findings.

**Comment by trevor-scheer** [comment]
The `parseBody` implementation expects JSON by default but you're welcome to override it for exactly this type of usage.
https://github.com/apollographql/datasource-rest#parsebody
