### ISSUE TITLE
RESTDataSource connection is not getting closed, having high weight time

### ISSUE THREAD

**Issue by Statowfiq** [apollographql/datasource-rest#30]
I am using apollo server with RESTDataSource to call the Rest APIs. When I did the load testing it is having lot of connection waits. I believe connection is not getting closed.

**Comment by trevor-scheer** [comment]
Hey, sorry for the delay. There aren't enough details here for us to reproduce the issue.

We're not doing anything special in the code here w.r.t. keep alive or anything that should keep the connections open longer than expected beyond node-fetch default behavior.
