### ISSUE TITLE
Question about cacheOptions

### ISSUE THREAD

**Issue by mlovatonv** [apollographql/datasource-rest#304]
Hello

I have this code:

```js
const cacheOptions = async (_url, response, request) => {
  const clonedResponse = await response.clone().json();

  const isSpecial = hasSpecialCondition(clonedResponse, request);

  if (isSpecial) {
    return { ttl: 5 };
  }

  return undefined;
}

class DuckSource extends BaseDataSource {
  async getDucks(params) {
    return await this.get('/api/ducks', { params, cacheOptions });
  }
}
```

I couldn't find an example of how the `cacheOptions` function should be used. So I have these questions:
- Is it supposed to be used like this?
- Can it have a negative effect in the server performance?
- Should I use `cacheOptionsFor` instead?

**Comment by trevor-scheer** [comment]
* That seems like a reasonable usage.
* I can't speak to how significant of a performance impact cloning the response has, that's something you'd need to measure yourself.
* You can think of `cacheOptionsFor` as the default for all* (non-`HEAD`) requests, whereas `cacheOptions` allows you to set the ttl on a per request basis.
