### ISSUE TITLE
[apollo-datasource-rest] (node:30845) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fetch' of undefined

### ISSUE THREAD

**Issue by wzup** [apollographql/datasource-rest#33]
### This bug report should include:

- [ ] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ ] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem. Other great ways to demonstrate a reproduction are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).
-->

First off, you **DO NOT** explain how one can obtain info you demand above. 
Hence I only add info I know how to obtain.

**server/package.json**
```
  "dependencies": {
    "apollo-datasource": "^0.1.3",
    "apollo-datasource-rest": "^0.1.5",
    "apollo-server": "2.6.1",
    "apollo-server-testing": "2.6.1",
    "graphql": "^14.2.1",
    "isemail": "^3.1.3",
    "nodemon": "^1.18.4",
    "sequelize": "^4.39.0",
    "sqlite3": "^4.0.3"
  },
```

## apollo-datasource-rest throws error in GET requersts

**The expected behavior.**
`const {RESTDataSource} = require('apollo-datasource-rest');` can make REST request without errors.

**The actual behavior.**
```
(node:30845) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fetch' of undefined
    at LaunchAPI.<anonymous> (/Users/admin//apollo/fullstack-tutorial/start/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:148:63)
    at Generator.next (<anonymous>)
    at /Users/admin//apollo/fullstack-tutorial/start/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/admin//apollo/fullstack-tutorial/start/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:3:12)
    at trace (/Users/admin//apollo/fullstack-tutorial/start/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:143:78)
    at LaunchAPI.<anonymous> (/Users/admin//apollo/fullstack-tutorial/start/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:186:24)
    at Generator.next (<anonymous>)
    at /Users/admin//apollo/fullstack-tutorial/start/server/node_modules/apollo-datasource-rest/dist/RESTDataSource.js:7:71
    at new Promise (<anonymous>)
(node:30845) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:30845) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**A simple, runnable reproduction!**
1. Follow your [Tutorial](https://www.apollographql.com/docs/tutorial)
2. Follow this step [Hook up your data sources](https://www.apollographql.com/docs/tutorial/data-source/) up to [Connect a database](https://www.apollographql.com/docs/tutorial/data-source/#connect-a-database) section (don't implement it)
3. Open `index.js` file and add the following lines:
```
const api = new LaunchAPI();
const launches = api.getAllLaunches(); // <== THIS THROWS
```

Why it doesn't work? 
What is `property 'fetch' of undefined`?

Related issue
https://github.com/apollographql/apollo-server/issues/3429

**Comment by trevor-scheer** [comment]
Sorry for the delay in response. This seems related to rest datasource's requirement of having `initialize` called on it.

In v4 of the rest datasource package, this is no longer part of the API.
