### ISSUE TITLE
Fix RESTDataSource fetching a path with a colon

### ISSUE THREAD

**Issue by brandon-leapyear** [apollographql/datasource-rest#36]
`RESTDataSource.resolveUrl` doesn't work correctly for paths with a colon, e.g.

```js
this.get('/foo:')
```

this throws

```
TypeError: Only absolute URLs are supported
```

The source code strips out the leading slash, which leads to the call `new URL('foo:', 'http://example.com')`, where `foo:` looks like an absolute URL without a host.

https://github.com/apollographql/apollo-server/blob/cd19cfeff260c4b948fb56f0b3b210a43858cc8c/packages/apollo-datasource-rest/src/RESTDataSource.ts#L74-L88

**Comment by glasser** [comment]
Duplicate of #23. Will pull your suggestion over there.
