### ISSUE TITLE
Feature request: apollo-datasource-rest transform output to minify cache

### ISSUE THREAD

**Issue by EloB** [apollographql/datasource-rest#43]
My app downloads a lot information from multiple external webpages. The problem is that one of them they doesn't have an API. So I making a simple GET request to their webpage but that request return a lot of HTML that I parse and extract like 10 characters. The problem is that cache stores everything and it's so much unnecessary information.

I was thinking if there was possible to have something like
```js
const response = await this.get(
  '/some/url',
  { some: 'query' },
  {
    cacheOptions: {
      ttl: 60 * 60 * 24,
    },
    // Want something like this to be executed once for each request but not when using cache.
    transform: (body) => { 
      const $ = cheerio.load(body);
      return $('.some-selector').text(); // Only cache this.
    }
  },
);
response // Should equal $('.some-selector').text() result
```

It could also be good transform big json objects into smaller object or fix bad data structure that doesn't fit your application.

I don't want todo something like this because it's inefficient:
```js
const response = await this.get(
  '/some/url',
  { some: 'query' },
  {
    cacheOptions: {
      ttl: 60 * 60 * 24,
    },
  },
);
const $ = cheerio.load(response);
const result = $('.some-selector').text();
```

**Comment by glasser** [comment]
This seems like a pretty niche use case. The cache in RESTDataSource is an HTTP-level cache; that cache is the main value for this class. If you'd like to cache some derived data, it's not too hard to just use a cache directly to cache that data (and not use an HTTP-level cache). If this is the only thing you're using RESTDataSource for, perhaps just use a non-caching HTTP client directly. Sorry for the delay!
