### ISSUE TITLE
Typescript definition improvement: RESTDataSource class async functions

### ISSUE THREAD

**Issue by sarink** [apollographql/datasource-rest#47]
The `RESTDataSource` class automatically explicitly declares a default type of `any` https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L47 for the async functions `get, post, etc`

We should force the user to declare the type. The library should not assume `any`.

As a workaround, I've been doing this, but it's very inconvenient because the code compiles and the type is simply inferred as `unknown`, which isn't immediately obvious to the consumer:

```
export class BaseDataSource extends RESTDataSource {
  constructor() {
    super();
  }

  protected async get<TResult>(...args: Parameters<RESTDataSource['get']>) {
    return super.get<TResult>(...args);
  }

  protected async post<TResult>(...args: Parameters<RESTDataSource['post']>) {
    return super.post<TResult>(...args);
  }

  protected async patch<TResult>(...args: Parameters<RESTDataSource['patch']>) {
    return super.patch<TResult>(...args);
  }

  protected async put<TResult>(...args: Parameters<RESTDataSource['put']>) {
    return super.put<TResult>(...args);
  }

  protected async delete<TResult>(...args: Parameters<RESTDataSource['delete']>) {
    return super.delete<TResult>(...args);
  }
}
```

**Comment by trevor-scheer** [comment]
@sarink, apologies for such a late follow up here. We're actively working through the issues here and plan on making a release with improvements soon.

I'm open to this suggestion but on the fence about it.

I see why a silently defaulted `any` can be a poor DX - there's really no "encouragement" from TypeScript to provide your expected `TResult`, so it's silently `any`.

On the other hand, I think people generally don't love having generics everywhere in their code. The default `any` is convenient for those who choose to leave it and yields the same outcome for those who want to leverage the `TResult` for stronger types.

Your workaround seems within reason to me, and someone wanting the default `any` behavior would have a nearly identical workaround that does the inverse.

My personal opinion leans just a bit in the direction you've proposed, but I'm more inclined to not make a breaking typings change on a preference that seems very debatable (and incurs a similar cost to users from both sides of the preference).

I'd be interested to hear additional opinions from users on this one.

**Comment by trevor-scheer** [comment]
Going to close this as "won't fix" since at least @glasser and I agree here. I think I would need to see either some additional benefit or a surprising number of people requesting this change to go forward with it (both of which I'm open to, just not expecting).
