### ISSUE TITLE
RESTDataSource delete method doesn't accept body param

### ISSUE THREAD

**Issue by redmundas** [apollographql/datasource-rest#52]
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L180
this method doesn't have body param to pas to request. could you add it? there's no reason to not support it because delete request supports it:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/DELETE

I know that the use of it is not recommended, but it's it's not prohibited either. and we're dealing with API that is using this kind of thing.

also, fetch method is private. so if any of the provided methods doesn't suit our needs, we're blocked from using this class.
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-datasource-rest/src/RESTDataSource.ts#L190
also other methods (like post, put or patch) doesn't accept params property. so I don't understand why you're limiting other methods only to body params.

Apollo version: 2

**Comment by trevor-scheer** [comment]
Sorry for the delay - this should just work in the `@apollo/datasource-rest` v4 package now (`.delete()` has a new signature which is equivalent to `.post()`).
