### ISSUE TITLE
Update fetch request options types in RequestInit

### ISSUE THREAD

**Issue by StarpTech** [apollographql/datasource-rest#71]
`apollo-datasource-rest` [fetch](https://github.com/apollographql/apollo-server/blob/1e4cf7734f1225c81e294a8fd7f637c9f6aa6003/packages/apollo-server-env/src/fetch.d.ts#L47-L71) types are out of sync with the used implementation. For example, the `signal` property is missing. 

https://github.com/node-fetch/node-fetch/tree/2.x#request-cancellation-with-abortsignal

**Comment by glasser** [comment]
We switched to a new set of TS typings (`@apollo/utils.fetcher`) in the new `@apollo/datasource-rest` v4. These typings are designed to maximize portability across multiple potential `fetch` implementations (eg, they don't let you use classes like `Request` or `Headers` which are not consistently detected across implementations). They also support `signal`! We are open to adding other missing options as long as they are supported portably by all conformant Fetch implementations (eg, they don't depend on `instanceof` checks against particular classes defined in one particular Fetch implementation).
