### ISSUE TITLE
POST request body is undefined when use willSendRequest

### ISSUE THREAD

**Issue by marcin-zajac** [apollographql/datasource-rest#83]
path : packages/apollo-datasource-rest/src/RESTDataSource.ts line 210
issue : POST request body is undefined when use willSendRequest
current code :
```
    const modifiedRequest: WillSendRequestOptions = {
      ...request,
      // guarantee params and headers objects before calling `willSendRequest` for convenience
      params:
        request.params instanceof URLSearchParams
          ? request.params
          : new URLSearchParams(request.params),
      headers: request.headers ?? Object.create(null),
      body: undefined,
    };
```

change required :
```
    const modifiedRequest: WillSendRequestOptions = {
      ...request,
      // guarantee params and headers objects before calling `willSendRequest` for convenience
      params:
        request.params instanceof URLSearchParams
          ? request.params
          : new URLSearchParams(request.params),
      headers: request.headers ?? Object.create(null),
    };
```

actual behavior : when use willSendRequest which post method in any class extends RESTDataSource every post request have missing body
 
expected behavior : when use willSendRequest request body is the same as defined by user  
 

reproduce : create any class extends RESTDataSource, create anyone POST request and try to use willSendRequest method. Body in this request will be undefined

**Comment by dariusbakunas** [comment]
Sort of related, but it also means there is no way to post `application/x-www-form-urlencoded` where body would be url encoded string, the condition after this block sets `modifiedRequest` body only if it is an object, this must be a bug

**Comment by marcin-zajac** [comment]
exactly :)

**Comment by dycor** [comment]
Any update ? It's been more than 3 weeks and this is critical

**Comment by trevor-scheer** [comment]
@dycor sure. I have a PR open as you can see in the updates on this issue.

A combination of holiday/vacation and other work priorities mean it's not ready to land just yet,but it's in progress and on my radar.

In the meantime, you're welcome to continue using the previous version of this package which doesn't have this regression or fork and patch it yourself until we release a fix for it. You're also welcome to try out the build from my PR and use it until we release a fix. I've solicited feedback for exactly that and would be happy to hear of it solves the issue for you. It's obviously WIP so use at your own risk.
